#!/bin/bash

# Author: Raya Sophia Casas
# Date: March 24, 2024

echo "Starting test runner..."

test_runner="C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe"
tests_dll="Project/x64/Debug/Unit Test.dll"
failure_string="Failed:"

testout="$("$test_runner" "$tests_dll")"

if echo "$testout" | grep -q "$failure_string"; then
    echo >&2 "Unit tests are not passing! Push aborted!"
    exit 1
fi

echo >&2 "All tests run successfully."
exit 0
